---
- name: Check if {{ item.name }} is currently in the dock
  ansible.builtin.command:
    cmd: dockutil --find {{ item.name | quote }}
  register: dock_item_exists
  changed_when: false
  failed_when: |
    "No such file or directory" in dock_item_exists.stdout

- name: Add {{ item.name }} to the dock
  ansible.builtin.command:
    cmd: dockutil --add {{ item.path | quote }} --no-restart
  when: dock_item_exists.rc > 0
  notify:
    - Kill dock
